apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgbackups.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgbackup
    listKind: PgbackupList
    plural: pgbackups
    singular: pgbackup
  scope: Namespaced
  version: v1
