apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgtasks.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgtask
    listKind: PgtaskList
    plural: pgtasks
    singular: pgtask
  scope: Namespaced
  version: v1
