apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgupgrades.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgupgrade
    listKind: PgupgradeList
    plural: pgupgrades
    singular: pgupgrade
  scope: Namespaced
  version: v1
